/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { Lock } from "./Lock";
export type { AddPoints } from "./AddPoints";
export type { ClaimTokens } from "./ClaimTokens";
