/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export { Lock__factory } from "./Lock__factory";
export { AddPoints__factory } from "./AddPoints__factory";
export { ClaimTokens__factory } from "./ClaimTokens__factory";
